[project]
name = "flog"
version = "1.0.7"
description = "taulog"
readme = "README.md"
requires-python = ">=3.5"
dependencies = [ "loguru>=0.7.3",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
